In [3]:
import torch
torch.cuda.is_available() # routine env not available; torchgpu is

False

In [9]:
a = torch.empty(3,4).normal_(0,1)
a

tensor([[ 0.4217,  2.5621, -0.1559,  0.2582],
        [-0.8521,  1.2065, -0.3532, -0.8034],
        [-0.3574,  0.2499, -0.1427,  0.1053]])

In [14]:
x, y = a.sort(1)

In [15]:
x

tensor([[-0.1559,  0.2582,  0.4217,  2.5621],
        [-0.8521, -0.8034, -0.3532,  1.2065],
        [-0.3574, -0.1427,  0.1053,  0.2499]])

In [17]:
y

tensor([[2, 3, 0, 1],
        [0, 3, 2, 1],
        [0, 2, 3, 1]])

In [21]:
4//3

1

In [23]:
a = x[:,:2]
b = x[:,2:]
a, b

(tensor([[-0.1559,  0.2582],
         [-0.8521, -0.8034],
         [-0.3574, -0.1427]]),
 tensor([[ 0.4217,  2.5621],
         [-0.3532,  1.2065],
         [ 0.1053,  0.2499]]))

In [27]:
a[:,-1:]
b[:,:1]

tensor([[ 0.4217],
        [-0.3532],
        [ 0.1053]])