In [1]:
import torch
torch.cuda.is_available() # routine env not available; torchgpu is

True

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [2]:
a = torch.empty(3,4).normal_(0,1)
a

tensor([[ 2.6434, -0.8545, -0.1619, -0.0312],
        [ 0.7908, -0.8453,  0.6126,  0.4575],
        [-1.3143,  1.0618,  2.1613, -1.4556]])

In [7]:
a.device
b = a.to(device)

In [9]:
# b
a

tensor([[ 2.6434, -0.8545, -0.1619, -0.0312],
        [ 0.7908, -0.8453,  0.6126,  0.4575],
        [-1.3143,  1.0618,  2.1613, -1.4556]])

In [8]:
# a.item()
a = torch.empty(1,).normal_()
a, a.item()

(tensor([-0.3757]), -0.37565407156944275)

In [14]:
x, y = a.sort(1)

In [15]:
x

tensor([[-0.1559,  0.2582,  0.4217,  2.5621],
        [-0.8521, -0.8034, -0.3532,  1.2065],
        [-0.3574, -0.1427,  0.1053,  0.2499]])

In [17]:
y

tensor([[2, 3, 0, 1],
        [0, 3, 2, 1],
        [0, 2, 3, 1]])

In [21]:
4//3

1

In [23]:
a = x[:,:2]
b = x[:,2:]
a, b

(tensor([[-0.1559,  0.2582],
         [-0.8521, -0.8034],
         [-0.3574, -0.1427]]),
 tensor([[ 0.4217,  2.5621],
         [-0.3532,  1.2065],
         [ 0.1053,  0.2499]]))

In [27]:
a[:,-1:]
b[:,:1]

tensor([[ 0.4217],
        [-0.3532],
        [ 0.1053]])

In [3]:
import numpy as np

In [6]:
np.logspace(-5,5,6)

array([1.e-05, 1.e-03, 1.e-01, 1.e+01, 1.e+03, 1.e+05])

In [7]:
i, x, y, z = 0, 1, 2, 3

In [11]:
print(f'{i}\t',
      f'{x}'
     )

0	 1
