#### Imports

In [1]:
import sys
sys.path.insert(0, '/home/fangming/projects/dredfish/packages/dredFISH')
sys.path.insert(0, '/home/fangming/projects/dredfish/packages/PySpots')
from dredFISH.Analysis.TissueGraph import *
from dredFISH.Visualization.Viz import *

import matplotlib.pyplot as plt 

#### Load data

In [2]:
%%time
base_path = '/bigstore/Images2021/gaby/dredFISH/DPNMF_PolyA_2021Nov19/'
dataset = 'DPNMF_PolyA_2021Nov19'

TMG = TissueMultiGraph()
XY,PNMF = TMG.load_and_normalize_data(base_path,dataset)

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
/home/fangming/projects/dredfish/packages/dredFISH/dredFISH/Analysis/TissueGraph.py:243: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  data.X = data.X/data.obs['total_signal'][:,None]


CPU times: user 1.13 s, sys: 817 ms, total: 1.95 s
Wall time: 1.95 s


#### Build layers 1-2: cells and zones

In [3]:
%%time
TMG.create_cell_and_zone_layers(XY,PNMF)


Calling initial optimization
 
 Func-count     x          f(x)          Procedure
    1        11.5208     -7.60178        initial
    2        18.5792     -7.35321        golden
    3        7.15843     -7.70148        golden
    4        4.46235     -7.49562        golden
    5        8.52661     -7.69949        parabolic
    6        7.74081     -7.73794        parabolic
    7         7.8336     -7.69651        parabolic
    8        7.51836     -7.69433        golden
    9        7.65584     -7.70754        golden
   10        7.77625     -7.71905        golden
   11        7.72251     -7.70388        parabolic
   12        7.75435      -7.7035        golden
   13        7.73382     -7.68911        golden
   14        7.74598     -7.70269        golden
   15        7.73748     -7.67691        golden

Optimization terminated successfully;
The returned value satisfies the termination criteria
(using xtol =  0.01 )
Number of types: 107 initial entropy: 7.737944071953079 number of eval

In [4]:
%%time
TMG.add_geoms()

CPU times: user 2min 4s, sys: 1.09 s, total: 2min 5s
Wall time: 2min 5s


In [5]:
%%time
# save Cond entropy values for later plotting
TMG.Layers[0].calc_entropy_at_different_Leiden_resolutions()

CPU times: user 8min 21s, sys: 4.31 s, total: 8min 25s
Wall time: 8min 23s


#### Build layers 3: regions

In [6]:
%%time
topics = TMG.find_topics(use_parallel=True)
TMG.create_region_layer(topics)


Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json


OSError: Connection file '~/.ipython/profile_default/security/ipcontroller-client.json' not found.
You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.

### Save

In [7]:
TMG.save('TMG_example_fx_v1.pkl')

In [10]:
dir(TMG)

['Geoms',
 'Layers',
 'N',
 'Ntypes',
 'Views',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'add_geoms',
 'add_view',
 'cell_attributes',
 'cond_entropy',
 'create_cell_and_zone_layers',
 'create_region_layer',
 'dview',
 'fill_holes',
 'find_regions_edge_level',
 'find_topics',
 'find_upstream_layer',
 'get_raster',
 'layers_graph',
 'load_and_normalize_data',
 'map_to_cell_level',
 'save']

In [11]:
TMG.cell_attributes

Empty DataFrame
Columns: []
Index: []

In [14]:
TG = TMG.Layers[0]

In [16]:
dir(TG)

['Dtype',
 'FG',
 'N',
 'Ntypes',
 'SG',
 'Type',
 'Type2',
 'UpstreamMap',
 'X',
 'XY',
 'Y',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'build_spatial_graph',
 'calc_entropy_at_different_Leiden_resolutions',
 'calc_type2',
 'cond_entropy',
 'cond_entropy_df',
 'contract_graph',
 'extract_environments',
 'feature_mat',
 'feature_type_mat',
 'gradient_magnitude',
 'graph_local_avg',
 'graph_local_median',
 'layer_type',
 'multilayer_Leiden_with_cond_entropy',
 'node_size',
 'type_freq',
 'watershed']

In [18]:
TG.SG

In [21]:
TG.XY

array([[-3747.98193262, -3741.71205264],
       [-3531.0757215 , -3742.43823527],
       [-3691.03543921, -3743.11154249],
       ...,
       [ 3037.9403606 , -2410.89280518],
       [ 2986.14603613, -2411.23177832],
       [ 3183.07582324, -2411.71982324]])

In [23]:
TG.feature_mat

ArrayView([[ 0.31305954,  0.16653173,  0.14215192, ...,  0.07231783,
             0.20829885,  0.18233976],
           [ 0.1240568 ,  0.37784585,  0.47153735, ...,  0.07814332,
             0.15456934,  0.21423572],
           [ 0.285935  ,  0.18951494,  0.14308624, ...,  0.20446725,
             0.21409354,  0.13887455],
           ...,
           [-0.08419434, -0.05871325, -0.04663565, ...,  0.02263566,
            -0.04005145, -0.0105409 ],
           [ 0.01110965,  0.01287316,  0.0361967 , ...,  0.9144609 ,
             0.04108392,  0.04593695],
           [ 0.20274548,  0.19979024,  0.18276827, ...,  0.22843441,
             0.15715098,  0.18876259]], dtype=float32)

In [24]:
TG.layer_type

'cells'

In [25]:
TG.Type

array([ 0.,  1.,  0., ..., 68., 22., 86.])

In [26]:
np.unique(TG.Type)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106.])