In [2]:
import numpy as np
import torch
import torch.nn as nn
from scipy import sparse
from scipy.spatial import cKDTree
import matplotlib.pyplot as plt

In [24]:
a = np.random.randn(5,5)
a = torch.from_numpy(a)
a

tensor([[-1.2293, -0.5155, -0.6905,  1.2327,  1.1107],
        [-1.1506,  0.9750,  0.4426, -0.8144, -1.1218],
        [-0.0499, -0.5111,  0.3017,  0.6251,  0.5436],
        [ 0.0792,  1.1404, -0.5099,  0.1341, -1.7320],
        [ 0.4275, -1.7578,  0.1583, -1.3798, -1.9259]], dtype=torch.float64)

In [77]:
a.square()

tensor([[1.5112e+00, 2.6573e-01, 4.7685e-01, 1.5196e+00, 1.2337e+00],
        [1.3238e+00, 9.5069e-01, 1.9591e-01, 6.6320e-01, 1.2583e+00],
        [2.4897e-03, 2.6119e-01, 9.0997e-02, 3.9075e-01, 2.9550e-01],
        [6.2669e-03, 1.3004e+00, 2.6000e-01, 1.7978e-02, 2.9997e+00],
        [1.8276e-01, 3.0900e+00, 2.5072e-02, 1.9039e+00, 3.7090e+00]],
       dtype=torch.float64)

In [75]:
nn.Dropout2d(p=0.5)(a.T).T*0.5

tensor([[-0.0000, -0.0000, -0.6905,  0.0000,  0.0000],
        [-0.0000,  0.0000,  0.4426, -0.0000, -0.0000],
        [-0.0000, -0.0000,  0.3017,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.5099,  0.0000, -0.0000],
        [ 0.0000, -0.0000,  0.1583, -0.0000, -0.0000]], dtype=torch.float64)

In [66]:
b = torch.reshape(a, (5,5,1))
(nn.Dropout2d(p=0.5)(b)*0.5)[:,:,0]

tensor([[-1.2293, -0.5155, -0.6905,  1.2327,  1.1107],
        [-1.1506,  0.9750,  0.4426, -0.8144, -1.1218],
        [-0.0499, -0.5111,  0.3017,  0.6251,  0.5436],
        [ 0.0792,  1.1404, -0.5099,  0.1341, -1.7320],
        [ 0.0000, -0.0000,  0.0000, -0.0000, -0.0000]], dtype=torch.float64)

In [19]:
torch.linalg.vector_norm(a, ord=0.5)


tensor(63.9107, dtype=torch.float64)

In [18]:
a.abs().sqrt().sum().square()

tensor(63.9107, dtype=torch.float64)

In [21]:
a.abs().sqrt().mean()

tensor(0.8883, dtype=torch.float64)

In [78]:
b = nn.Embedding(5,3).weight
b

Parameter containing:
tensor([[-1.7015,  0.9601,  1.3410],
        [ 0.1451,  1.9209, -0.6823],
        [-0.5052,  1.0389, -0.8035],
        [ 0.1943,  0.2546, -1.3593],
        [-0.5392, -0.6962, -0.0749]], requires_grad=True)

In [79]:
b.exp().mean()

tensor(1.5836, grad_fn=<MeanBackward0>)

In [89]:
b.square()

tensor([[2.8951, 0.9217, 1.7984],
        [0.0211, 3.6899, 0.4656],
        [0.2552, 1.0793, 0.6457],
        [0.0378, 0.0648, 1.8476],
        [0.2907, 0.4847, 0.0056]], grad_fn=<PowBackward0>)

In [82]:
b**2

tensor([[2.8951, 0.9217, 1.7984],
        [0.0211, 3.6899, 0.4656],
        [0.2552, 1.0793, 0.6457],
        [0.0378, 0.0648, 1.8476],
        [0.2907, 0.4847, 0.0056]], grad_fn=<PowBackward0>)

In [83]:
nn.Dropout2d(p=0.5)(b) #(a.T).T*0.5

tensor([[-0.0000,  0.0000,  0.0000],
        [ 0.2902,  3.8418, -1.3647],
        [-0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000]], grad_fn=<SqueezeBackward1>)

In [98]:
(nn.Dropout(0.1)(b))

tensor([[-1.8906,  0.0000,  1.4900],
        [ 0.1612,  2.1343, -0.7582],
        [-0.5613,  1.1543, -0.8928],
        [ 0.2159,  0.2829, -1.5103],
        [-0.5991, -0.7736, -0.0832]], grad_fn=<MulBackward0>)